language: python
python:
    - 3.7
addons:
    postgresql: "9.6"
install:
    - travis_retry pip install tox tox-travis coveralls
before_script:
    - export PGDATA=$(psql -c "SHOW data_directory;" -F "" -A -t -U postgres)
    - echo "max_prepared_transactions = 10" | sudo tee -a /etc/postgresql/9.6/main/postgresql.conf
    - sudo /etc/init.d/postgresql restart
    - psql -c "create user pjpersist with createdb password 'pjpersist';" -U postgres
script:
    - tox
notifications:
    email: false
after_success:
    - coveralls
